/**
 * Cloudflare Pages Function — EC2 On-Demand Pricing (snapshot)
 * Route: GET /api/aws/ec2-pricing/on-demand
 *
 * Serves a pre-built snapshot of AWS EC2 on-demand pricing for the
 * default-visible filters AWS shows on aws.amazon.com/ec2/pricing/on-demand
 * (US East / N. Virginia, Linux, Shared, no preinstalled software).
 *
 * The snapshot is generated by `scripts/fetch-aws-ec2-pricing.mjs` from
 * the official AWS Price List bulk CSV — see that script's header for
 * the exact source and filter rules. We don't fetch the bulk CSV at
 * runtime because it's ~295MB and would blow the Pages Functions CPU
 * budget on every cold-cache request.
 *
 * Query params (optional):
 *   ?q=<substring>       — filter rows where instance_type starts with q
 *                          (case-insensitive). Used by the dashboard's
 *                          search box.
 *   ?limit=N             — cap the row count (default 50, max 1500)
 *   ?offset=N            — skip first N rows (paging)
 *   ?sort=type|price     — default: price asc. type = instance_type asc.
 */

import {
  onDemandRows,
  region,
  regionLabel,
  operatingSystem,
  tenancy,
  generatedAt,
  awsReferenceCount,
  awsReferenceCountDate,
} from './_on-demand-data.js';

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, OPTIONS',
};

export async function onRequestGet({ request }) {
  const url = new URL(request.url);
  const q = (url.searchParams.get('q') || '').trim().toLowerCase();
  const limit = Math.min(Math.max(parseInt(url.searchParams.get('limit') || '50', 10) || 50, 1), 1500);
  const offset = Math.max(parseInt(url.searchParams.get('offset') || '0', 10) || 0, 0);
  const sort = url.searchParams.get('sort') || 'price';

  let rows = onDemandRows;
  if (q) {
    rows = rows.filter(r => r.instance_type.toLowerCase().includes(q));
  }
  if (sort === 'type') {
    rows = rows.slice().sort((a, b) => a.instance_type.localeCompare(b.instance_type));
  } else {
    // already price-asc in the static data; resort defensively in case
    // a future filter accidentally permutes
    rows = rows.slice().sort((a, b) => a.price_per_hour_usd - b.price_per_hour_usd);
  }

  const total = rows.length;
  const slice = rows.slice(offset, offset + limit);

  return new Response(JSON.stringify({
    success: true,
    region,
    region_label: regionLabel,
    operating_system: operatingSystem,
    tenancy,
    generated_at: generatedAt,
    total_rows: onDemandRows.length,
    matched_rows: total,
    aws_reference_count: awsReferenceCount,
    aws_reference_count_date: awsReferenceCountDate,
    offset,
    limit,
    rows: slice,
    source: 'AWS Price List bulk CSV — pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/us-east-1/index.csv',
  }), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': 'public, max-age=300',
      ...CORS,
    },
  });
}

export async function onRequestOptions() {
  return new Response(null, { status: 204, headers: CORS });
}
